services:
  postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    networks:
      - app_net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-api
    networks:
      - app_net
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

#    ports:
#      - "${APP_PORT}:${APP_PORT}"

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge